name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    concurrency:
      group: preview-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🧪 Run tests & generate report
        run: |
          mvn clean test
          mvn verify

      - name: 🚀 Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: target/cucumber-html-reports
