name: Delete PR Preview

on:
  pull_request:
    types: [closed]

jobs:
  delete-preview:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: 🧹 Delete PR preview folder
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: pr-preview
          action: remove
