name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  pr-preview:
    runs-on: ubuntu-latest
    concurrency:
      group: preview-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🔄 Clean target folder
        run: rm -rf target

      - name: 🧪 Run tests & generate report
        run: |
          mvn clean test
          mvn verify

      - name: 📂 Add redirect index.html to report folder
        run: |
          echo '<html><head><meta http-equiv="refresh" content="0; URL=report-feature_1773788758.html" /></head><body></body></html>' > target/cucumber-html-reports/index.html

      - name: 🚀 Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: target/cucumber-html-reports
